language: node_js
node_js:
  - stable
script:
  - npm run prod
  - "travis_wait 30 sleep 1800 &"
  - curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist