import '../styles.scss';
import '../blocks/menu-toggler/menu-toggler';
import '../components/search-field/search-field';
import '../components/button/button';
import '../components/arrow-button/arrow-button';
import '../blocks/rotator/rotator';
import '../components/air-videoplayer/air-videoplayer';
import '../blocks/footer/footer';
var hideElement = require('./nojs');
hideElement('.page-header__main-nav-wrapper');