import './styles.scss';
import './blocks/button/button';
import './blocks/arrow-button/arrow-button';
import './blocks/slider/slider';
import './blocks/toggle/toggle';
import './blocks/search-field/search-field';
import './blocks/location/location';
import './blocks/calendar/calendar';
import './blocks/air-videoplayer/air-videoplayer';